name: Sync GitHub to Gitee

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      # 配置 Gitee 登录信息
      - name: Add Gitee remote
        run: |
          git config --global user.name "shiinayuki"
          git config --global user.email "2580647590@qq.com"
          git remote add gitee https://shiinayuki:${{ secrets.GITEE_TOKEN }}@gitee.com/shiinayuki/alas.puls.314.git

      # 强制同步到 Gitee
      - name: Push to Gitee
        run: |
          git push --force gitee HEAD:master
